package cu.uci.coj.Application.dao;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteDatabase.CursorFactory;
import android.database.sqlite.SQLiteOpenHelper;
import android.util.Log;
import de.greenrobot.dao.AbstractDaoMaster;
import de.greenrobot.dao.identityscope.IdentityScopeType;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * Master of DAO (schema version 1): knows all DAOs.
*/
public class DaoMaster extends AbstractDaoMaster {
    public static final int SCHEMA_VERSION = 1;

    /** Creates underlying database table using DAOs. */
    public static void createAllTables(SQLiteDatabase db, boolean ifNotExists) {
        DBProblemItemDao.createTable(db, ifNotExists);
        DBProblemDao.createTable(db, ifNotExists);
        DBEntriesDao.createTable(db, ifNotExists);
        DBJudgmentsDao.createTable(db, ifNotExists);
        DBUserStandingDao.createTable(db, ifNotExists);
        DBCountryStandingDao.createTable(db, ifNotExists);
        DBInstitutionStandingDao.createTable(db, ifNotExists);
        DBComingContestDao.createTable(db, ifNotExists);
        DBPreviousContestDao.createTable(db, ifNotExists);
        DBRunningContestDao.createTable(db, ifNotExists);
        DBProfileDao.createTable(db, ifNotExists);
        DBInboxMessageDao.createTable(db, ifNotExists);
        DBOutboxMessageDao.createTable(db, ifNotExists);
        DBDraftMessageDao.createTable(db, ifNotExists);
        DBFaqDao.createTable(db, ifNotExists);
    }
    
    /** Drops underlying database table using DAOs. */
    public static void dropAllTables(SQLiteDatabase db, boolean ifExists) {
        DBProblemItemDao.dropTable(db, ifExists);
        DBProblemDao.dropTable(db, ifExists);
        DBEntriesDao.dropTable(db, ifExists);
        DBJudgmentsDao.dropTable(db, ifExists);
        DBUserStandingDao.dropTable(db, ifExists);
        DBCountryStandingDao.dropTable(db, ifExists);
        DBInstitutionStandingDao.dropTable(db, ifExists);
        DBComingContestDao.dropTable(db, ifExists);
        DBPreviousContestDao.dropTable(db, ifExists);
        DBRunningContestDao.dropTable(db, ifExists);
        DBProfileDao.dropTable(db, ifExists);
        DBInboxMessageDao.dropTable(db, ifExists);
        DBOutboxMessageDao.dropTable(db, ifExists);
        DBDraftMessageDao.dropTable(db, ifExists);
        DBFaqDao.dropTable(db, ifExists);
    }
    
    public static abstract class OpenHelper extends SQLiteOpenHelper {

        public OpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory, SCHEMA_VERSION);
        }

        @Override
        public void onCreate(SQLiteDatabase db) {
            Log.i("greenDAO", "Creating tables for schema version " + SCHEMA_VERSION);
            createAllTables(db, false);
        }
    }
    
    /** WARNING: Drops all table on Upgrade! Use only during development. */
    public static class DevOpenHelper extends OpenHelper {
        public DevOpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory);
        }

        @Override
        public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
            Log.i("greenDAO", "Upgrading schema from version " + oldVersion + " to " + newVersion + " by dropping all tables");
            dropAllTables(db, true);
            onCreate(db);
        }
    }

    public DaoMaster(SQLiteDatabase db) {
        super(db, SCHEMA_VERSION);
        registerDaoClass(DBProblemItemDao.class);
        registerDaoClass(DBProblemDao.class);
        registerDaoClass(DBEntriesDao.class);
        registerDaoClass(DBJudgmentsDao.class);
        registerDaoClass(DBUserStandingDao.class);
        registerDaoClass(DBCountryStandingDao.class);
        registerDaoClass(DBInstitutionStandingDao.class);
        registerDaoClass(DBComingContestDao.class);
        registerDaoClass(DBPreviousContestDao.class);
        registerDaoClass(DBRunningContestDao.class);
        registerDaoClass(DBProfileDao.class);
        registerDaoClass(DBInboxMessageDao.class);
        registerDaoClass(DBOutboxMessageDao.class);
        registerDaoClass(DBDraftMessageDao.class);
        registerDaoClass(DBFaqDao.class);
    }
    
    public DaoSession newSession() {
        return new DaoSession(db, IdentityScopeType.Session, daoConfigMap);
    }
    
    public DaoSession newSession(IdentityScopeType type) {
        return new DaoSession(db, type, daoConfigMap);
    }
    
}
