package cu.uci.coj.Application.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "DBCOMING_CONTEST".
 */
public class DBComingContest {

    private Long id;
    private long startTime;
    /** Not-null value. */
    private String comingContest;

    public DBComingContest() {
    }

    public DBComingContest(Long id) {
        this.id = id;
    }

    public DBComingContest(Long id, long startTime, String comingContest) {
        this.id = id;
        this.startTime = startTime;
        this.comingContest = comingContest;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getStartTime() {
        return startTime;
    }

    public void setStartTime(long startTime) {
        this.startTime = startTime;
    }

    /** Not-null value. */
    public String getComingContest() {
        return comingContest;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setComingContest(String comingContest) {
        this.comingContest = comingContest;
    }

}
