package cu.uci.coj.Application.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "DBCOUNTRY_STANDING".
 */
public class DBCountryStanding {

    private Long id;
    private int rank;
    /** Not-null value. */
    private String countryStanding;

    public DBCountryStanding() {
    }

    public DBCountryStanding(Long id) {
        this.id = id;
    }

    public DBCountryStanding(Long id, int rank, String countryStanding) {
        this.id = id;
        this.rank = rank;
        this.countryStanding = countryStanding;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getRank() {
        return rank;
    }

    public void setRank(int rank) {
        this.rank = rank;
    }

    /** Not-null value. */
    public String getCountryStanding() {
        return countryStanding;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCountryStanding(String countryStanding) {
        this.countryStanding = countryStanding;
    }

}
