package cu.uci.coj.Application.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "DBFAQ".
 */
public class DBFaq {

    private Long id;
    /** Not-null value. */
    private String faqs;

    public DBFaq() {
    }

    public DBFaq(Long id) {
        this.id = id;
    }

    public DBFaq(Long id, String faqs) {
        this.id = id;
        this.faqs = faqs;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getFaqs() {
        return faqs;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFaqs(String faqs) {
        this.faqs = faqs;
    }

}
