package cu.uci.coj.Application.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "DBINSTITUTION_STANDING".
 */
public class DBInstitutionStanding {

    private Long id;
    private int rank;
    /** Not-null value. */
    private String institutionStanding;

    public DBInstitutionStanding() {
    }

    public DBInstitutionStanding(Long id) {
        this.id = id;
    }

    public DBInstitutionStanding(Long id, int rank, String institutionStanding) {
        this.id = id;
        this.rank = rank;
        this.institutionStanding = institutionStanding;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getRank() {
        return rank;
    }

    public void setRank(int rank) {
        this.rank = rank;
    }

    /** Not-null value. */
    public String getInstitutionStanding() {
        return institutionStanding;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setInstitutionStanding(String institutionStanding) {
        this.institutionStanding = institutionStanding;
    }

}
