package cu.uci.coj.Application.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "DBPREVIOUS_CONTEST".
 */
public class DBPreviousContest {

    private Long id;
    private long startTime;
    /** Not-null value. */
    private String previousContest;

    public DBPreviousContest() {
    }

    public DBPreviousContest(Long id) {
        this.id = id;
    }

    public DBPreviousContest(Long id, long startTime, String previousContest) {
        this.id = id;
        this.startTime = startTime;
        this.previousContest = previousContest;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getStartTime() {
        return startTime;
    }

    public void setStartTime(long startTime) {
        this.startTime = startTime;
    }

    /** Not-null value. */
    public String getPreviousContest() {
        return previousContest;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPreviousContest(String previousContest) {
        this.previousContest = previousContest;
    }

}
