package cu.uci.coj.Application.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "DBUSER_STANDING".
 */
public class DBUserStanding {

    private Long id;
    private int rank;
    /** Not-null value. */
    private String userStanding;

    public DBUserStanding() {
    }

    public DBUserStanding(Long id) {
        this.id = id;
    }

    public DBUserStanding(Long id, int rank, String userStanding) {
        this.id = id;
        this.rank = rank;
        this.userStanding = userStanding;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getRank() {
        return rank;
    }

    public void setRank(int rank) {
        this.rank = rank;
    }

    /** Not-null value. */
    public String getUserStanding() {
        return userStanding;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUserStanding(String userStanding) {
        this.userStanding = userStanding;
    }

}
